name: Multi-platform and Java Versions CI

on:
  schedule:
    - cron: "30 12 * * 3"
    - cron: "00 22 * * 5"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # параллельное выполнение для разных платформ и версий Java
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['11', '17', '8']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      
      - name: Run tests with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
